spring.application.name=demo

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Dialect line removed for HHH90000025 warning

# Server
server.port=${PORT:8080}

# CORS
cors.allowed-origins=http://localhost:5173,http://localhost:3000,http://localhost:5174,https://application-tracker-1-qdtg.onrender.com

# Jackson
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=Asia/Kolkata

groq.api.key=${GROQ_API_KEY}
