spring.application.name=demo

spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.keqwrfkutrawnloqavft
spring.datasource.password=#Manisha6299135594

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080